### ISSUE TITLE
Working with modded lily-pads

### ISSUE THREAD

**Issue by HanatakeYurii** [MehVahdJukaar/betterlily-multi#2]
Hi,
First thing I wanna thank you for this little ingenious mod, it's a very clever use of the waterlogging and the decoration possibilities are very nice.

I've tried it a bit and works like a charm, but I encountered a somewhat strange behavior with modded lily-pads, in my case Chipped's lily-pads. It's not game-breaking in any case: when I try to place a lantern on a modded lily-pad, the lily-pad waterlogs as a Vanilla lili-pad.

Would there be any way to replicate the behavior you introduced to all (tagged) lily-pads without 'reverting' them to vanilla?

**Comment by MehVahdJukaar** [comment]
Hm two way I could do this. I cou either make the waterlogged lily a tile entity or register a new block for each modded pad dynamically. Not sure what's best. First is easier but could be slow when many are paced

**Comment by HanatakeYurii** [comment]
I guess the first would be the heaviest performance-side (I have bad record tracking down too much entities on servers).
The second would be doing as Vertical Slabs Compat, somewhat, which would probably be better (plus, there should not be many modded lily-pads).

But anyways I don't you to pressure you on doing anything, you could just leave it as it is if you think it's not worth.

Thanks for your response.

**Comment by MehVahdJukaar** [comment]
already did it with first way. tile entites are not entities and if they dont tick/have custom render their impact only affect stuff that iterates over all of them or minimally save time as its slightly more stuff to be saved. did it this way as i dont have technology to dynamically alter non baked json models to lower them as they would need to be, plus im sure some rendering issue would hav arisen there for sure while just using a dynamic baked model that uses the original model directly seems the better option here

**Comment by HanatakeYurii** [comment]
Okay, I got you there. I guess my problem was linked to your description (too many chests having custom render or empty furnaces still ticking, something like that). 
I'll let you decide what you see fit, if that's worth or not.

**Comment by HanatakeYurii** [comment]
Thank you very much for your update
