### ISSUE TITLE
Crash on 1.20-1.2.0 on Minecraft 1.19.2

### ISSUE THREAD

**Issue by Dekamir** [MehVahdJukaar/betterlily-multi#3]
Fabric 0.14.21 - 1.19.2
Windows 10 22H2 x64, OpenJDK Temurin 17.0.5

[Crash log available here.](https://gist.github.com/Dekamir/106a0acf16679cc34d8dd023ff8c3534)

**Comment by MehVahdJukaar** [comment]
fixed
